import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Rudraksh Udiya | AWS Certified Data Engineer | Full Stack MERN | DSA | AIML",
  description: "B.Tech IT student with expertise in Cloud & Data Engineering (AWS DEA-C01), Full-Stack MERN Development, DSA, and AI/ML. Explore projects, the NEXUS AI assistant, live algorithm visualizer, and AWS pipeline showcase.",
  keywords: [
    "rudraksh udiya",
    "aws certified data engineer",
    "DEA-C01",
    "cloud data engineering",
    "aws data pipeline",
    "full stack developer",
    "mern stack developer",
    "react developer",
    "nextjs developer",
    "portfolio",
    "dsa algorithms",
    "data structures",
    "aiml developer",
    "machine learning",
    "aws s3 glue redshift",
    "nodejs",
    "typescript",
    "mongodb",
    "tailwindcss",
    "framer-motion",
    "web development",
    "software engineer",
    "frontend developer",
    "backend developer",
    "ui/ux",
    "responsive design",
  ] as Array<string>,
  authors: {
    name: "Rudraksh Udiya",
    url: "https://github.com/rudraksha127",
  },
  creator: "Rudraksh Udiya",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://github.com/rudraksha127/Portfolio",
    title: "Rudraksh Udiya | AWS Data Engineer & Full Stack Developer",
    description: "AWS Certified Data Engineer (DEA-C01) & Full Stack MERN Developer. See live AWS pipeline demos, DSA visualizer, and AI assistant.",
    siteName: "Rudraksh Udiya Portfolio",
  },
  twitter: {
    card: "summary_large_image",
    title: "Rudraksh Udiya | AWS Data Engineer & Full Stack Developer",
    description: "AWS Certified Data Engineer (DEA-C01) & Full Stack MERN Developer. See live AWS pipeline demos, DSA visualizer, and AI assistant.",
    creator: "@rudraksha127",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
} as const;
