import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Rudraksh Udiya | Full Stack Developer Portfolio",
  description: "Full Stack Developer specializing in React, Next.js, Node.js, and modern web technologies. Explore my projects, skills, and professional experience in building scalable web applications.",
  keywords: [
    "rudraksh udiya",
    "full stack developer",
    "web developer",
    "react developer",
    "nextjs developer",
    "portfolio",
    "reactjs",
    "nextjs",
    "nodejs",
    "typescript",
    "javascript",
    "mongodb",
    "tailwindcss",
    "framer-motion",
    "web development",
    "software engineer",
    "frontend developer",
    "backend developer",
    "mern stack",
    "ui/ux",
    "responsive design",
  ] as Array<string>,
  authors: {
    name: "Rudraksh Udiya",
    url: "https://github.com/rudraksha127",
  },
  creator: "Rudraksh Udiya",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://github.com/rudraksha127/Portfolio",
    title: "Rudraksh Udiya | Full Stack Developer",
    description: "Full Stack Developer specializing in React, Next.js, Node.js, and modern web technologies.",
    siteName: "Rudraksh Udiya Portfolio",
  },
  twitter: {
    card: "summary_large_image",
    title: "Rudraksh Udiya | Full Stack Developer",
    description: "Full Stack Developer specializing in React, Next.js, Node.js, and modern web technologies.",
    creator: "@rudraksha127",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
} as const;
